"""Create ai_metric table

Revision ID: 52cf3dd935c5
Revises: a5b3e9222a08
Create Date: 2025-05-15 17:53:12.109467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cf3dd935c5'
down_revision = 'a5b3e9222a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('move_time', sa.Float(), nullable=False),
    sa.Column('move_quality', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_streak')
        batch_op.drop_column('last_played')
        batch_op.drop_column('draws')
        batch_op.drop_column('wins')
        batch_op.drop_column('losses')
        batch_op.drop_column('highest_streak')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_streak', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.INTEGER(), nullable=True))

    op.drop_table('ai_metric')
    # ### end Alembic commands ###
