"""Add user stats columns

Revision ID: a5b3e9222a08
Revises: 
Create Date: 2025-04-19 18:53:35.395644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b3e9222a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('highest_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_streak')
        batch_op.drop_column('highest_streak')
        batch_op.drop_column('last_played')
        batch_op.drop_column('draws')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
